#Custom theme combining Booberry and Mellow
# https://github.com/helix-editor/helix/blob/master/runtime/themes/boo_berry.toml
# https://github.com/helix-editor/helix/blob/master/runtime/themes/mellow.toml
# https://github.com/ShadowTheCookie/linux_config/blob/main/helix/cookiestheme.toml


"attribute" = { fg = "neon_pink", modifiers = ["italic"] }

"keyword" = { fg = "neon_magenta" }
"keyword.control.conditional" = { fg = "neon_magenta", modifiers = ["italic"] }
"keyword.directive" = { fg = "electric_violet" }

"namespace" = { fg = "bright_lilac", modifiers = ["italic"] }


"punctuation" = { fg = "soft_violet" }
"punctuation.delimiter" = { fg = "soft_violet" }

"operator" = { fg = "neon_pink" }
"special" = { fg = "rose_bright" }


"variable" = { fg = "bright_lilac" }
"variable.builtin" = { fg = "electric_violet" }
"variable.parameter" = { fg = "neon_pink" }
"variable.other.member" = { fg = "lavender" }


"type" = { fg = "electric_violet" }
"type.builtin" = { fg = "orchid_bright" }
"type.enum.variant" = { fg = "orchid_bright" }

"constructor" = { fg = "rose_bright" }


"function" = { fg = "white_lavender" }
"function.macro" = { fg = "neon_magenta" }
"function.builtin" = { fg = "electric_violet" }


"tag" = { fg = "rose_bright" }


"comment" = { fg = "soft_violet", modifiers = ["italic"] }


"string" = { fg = "rose" }
"string.regexp" = { fg = "neon_pink" }
"string.special" = { fg = "lavender" }


"constant" = { fg = "orchid_bright" }
"constant.builtin" = { fg = "rose_bright" }
"constant.numeric" = { fg = "neon_magenta" }
"constant.character.escape" = { fg = "bright_lilac" }


"label" = { fg = "neon_pink" }


"markup.heading.marker" = { fg = "soft_violet" }
"markup.heading" = { fg = "white_lavender", modifiers = ["bold"] }
"markup.list" = { fg = "neon_magenta" }
"markup.bold" = { modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.strikethrough" = { modifiers = ["crossed_out"] }
"markup.link.url" = { fg = "electric_violet", modifiers = ["underlined"] }
"markup.link.text" = { fg = "neon_pink", modifiers = ["italic"] }
"markup.quote" = { fg = "soft_violet" }
"markup.raw" = { fg = "lavender" }


"diff.plus" = { fg = "white_lavender" }
"diff.minus" = { fg = "neon_pink" }
"diff.delta" = { fg = "electric_violet" }


"ui.background" = { bg = "berry" }
"ui.background.separator" = { fg = "soft_violet" }


"ui.linenr" = { fg = "soft_violet" }
"ui.linenr.selected" = { fg = "bright_lilac" }


"ui.statusline" = { fg = "bright_lilac", bg = "berry_saturated" }
"ui.statusline.inactive" = { fg = "soft_violet", bg = "berry_saturated", modifiers = ["dim"] }
"ui.statusline.normal" = { fg = "berry_saturated", bg = "bright_lilac", modifiers = ["bold"] }
"ui.statusline.insert" = { fg = "berry_saturated", bg = "neon_pink", modifiers = ["bold"] }
"ui.statusline.select" = { fg = "berry_saturated", bg = "electric_violet", modifiers = ["bold"] }


"ui.popup" = { fg = "bright_lilac", bg = "berry_saturated" }
"ui.window" = { fg = "soft_violet", bg = "berry" }
"ui.help" = { fg = "bright_lilac", bg = "berry_saturated" }


"ui.text" = { fg = "bright_lilac" }
"ui.text.focus" = { fg = "neon_pink" }


"ui.virtual" = { fg = "berry_fade" }
"ui.virtual.ruler" = { bg = "berry_dim" }
"ui.virtual.indent-guide" = { fg = "berry_fade" }
"ui.virtual.inlay-hint" = { fg = "soft_violet" }


"ui.selection" = { bg = "berry_dim" }
"ui.selection.primary" = { bg = "berry_dim" }



"ui.cursor" = { fg = "berry", bg = "neon_pink" }
"ui.cursor.match" = { fg = "berry", bg = "electric_violet" }
"ui.cursorline.primary" = { bg = "dim_berry" }

"ui.menu" = { fg = "bright_lilac", bg = "berry_saturated" }
"ui.menu.selected" = { fg = "white_lavender", bg = "berry_dim" }
"ui.menu.scroll" = { fg = "soft_violet", bg = "berry_saturated" }


"diagnostic.warning" = { underline = { color = "rose_bright", style = "curl" } }
"diagnostic.error" = { underline = { color = "neon_pink", style = "curl" } }
"diagnostic.info" = { underline = { color = "electric_violet", style = "curl" } }
"diagnostic.hint" = { underline = { color = "bright_lilac", style = "curl" } }

"diagnostic.unnecessary" = { modifiers = ["dim"] }
"diagnostic.deprecated" = { modifiers = ["crossed_out"] }


warning = "rose_bright"
error = "neon_pink"
info = "electric_violet"
hint = "bright_lilac"


[palette]

berry = "#171022"
berry_fade = "#3F2958"
berry_dim = "#2C1D42"
berry_saturated = "#0C0612"

soft_violet = "#B994EA"

neon_pink = "#FFAFD8"
neon_magenta = "#FA96E1"

rose = "#FCAECF"
rose_bright = "#FFE3F0"

bright_lilac = "#E2D5F8"
lavender = "#ECF0FA"
white_lavender = "#FFFFFF"

electric_violet = "#D5A3FF"
orchid_bright = "#F5CEFF"


bg = "#171022"
fg = "#ECF0FA"

black = "#050309"
bright_black = "#2C1D42"

red = "#FFAFD8"
bright_red = "#FFCBE5"

green = "#E2D5F8"
bright_green = "#FFFFFF"

yellow = "#FCAECF"
bright_yellow = "#FFE3F0"

blue = "#ECF0FA"
bright_blue = "#FFFFFF"

cyan = "#D5A3FF"
bright_cyan = "#F5CEFF"

white = "#ECF0FA"
bright_white = "#FFFFFF"


gray01 = "#0C0612"
gray02 = "#2C1D42"
gray03 = "#3F2958"
gray04 = "#B994EA"
gray05 = "#CDB2F0"
gray06 = "#E1D2F6"
gray07 = "#ECF0FA"
